version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: ofs_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '12345678'
      POSTGRES_DB: order_fulfillment
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ofs-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: ofs_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - ofs-network

  backend:
    build:
      context: ./backend
    container_name: ofs_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:12345678@db:5432/order_fulfillment?schema=public
      - JWT_SECRET=super_secret_enterprise_key_2026
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - ofs-network

  frontend:
    build:
      context: ./frontend
    container_name: ofs_frontend
    restart: always
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - ofs-network

networks:
  ofs-network:
    driver: bridge

volumes:
  postgres_data:
